In [1]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
import warnings
warnings.filterwarnings("ignore")

In [4]:
df1 = pd.read_csv('customers_Data.csv')
df1.head()

,customer_id,name,age,gender,city,occupation,income,signup_date
0,CID_001,Rahul,45,Male,Kolkata,Manager,1783745.0,15-07-2018
1,CID_002,Karan,58,Male,Kolkata,Consultant,1732758.0,30-01-2020
2,CID_003,Rahul,67,Male,Pune,Clerk,1487319.0,04-08-2018
3,CID_004,Pallavi,68,Female,Pune,Designer,406264.0,08-08-2024
4,CID_005,Sneha,19,Female,Noida,Office Intern,108779.0,29-07-2025

In [5]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   customer_id  5000 non-null   object
 1   name         5000 non-null   object
 2   age          5000 non-null   int64
 3   gender       5000 non-null   object
 4   city         5000 non-null   object
 5   occupation   5000 non-null   object
 6   income       4207 non-null   float64
 7   signup_date  5000 non-null   object
dtypes: float64(1), int64(1), object(6)
memory usage: 312.6+ KB

### Find a null value and duplicated value

In [6]:
n1  =  df1.isnull().sum()
n1

customer_id      0
name             0
age              0
gender           0
city             0
occupation       0
income         793
signup_date      0
dtype: int64

#### Handling null values

In [7]:
df1["income"] = df1["income"].fillna(df1["income"].mean())

In [8]:
df1.isnull().sum()

customer_id    0
name           0
age            0
gender         0
city           0
occupation     0
income         0
signup_date    0
dtype: int64

In [9]:
d1 = df1.duplicated().sum()
d1

np.int64(0)

### check data types

In [10]:
df1.dtypes

customer_id     object
name            object
age              int64
gender          object
city            object
occupation      object
income         float64
signup_date     object
dtype: object

#### change data type

In [11]:
df1["signup_date"] = pd.to_datetime(df1["signup_date"])

In [12]:
df1.dtypes

customer_id            object
name                   object
age                     int64
gender                 object
city                   object
occupation             object
income                float64
signup_date    datetime64[ns]
dtype: object

In [13]:
df1.to_csv("customers.csv", index=False)

# 2) transactions_data table

In [14]:
df2 =  pd.read_csv('transactions_Data.csv')
df2.head()

,transaction_id,account_id,transaction_type,amount,transaction_date,payment_method
0,TRN_00001,ACC_3550,Transfers,17462.31,16-08-2024,Cash
1,TRN_00002,ACC_2459,Withdrawals,157225.79,11-03-2024,IMPS
2,TRN_00003,ACC_4914,Transfers,80655.85,01-03-2023,Debit Card
3,TRN_00004,ACC_3150,Deposits,177471.95,20-01-2023,Debit Card
4,TRN_00005,ACC_2272,Deposits,11726.54,27-03-2022,IMPS

In [15]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 6 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   transaction_id    50000 non-null  object
 1   account_id        50000 non-null  object
 2   transaction_type  50000 non-null  object
 3   amount            50000 non-null  float64
 4   transaction_date  50000 non-null  object
 5   payment_method    50000 non-null  object
dtypes: float64(1), object(5)
memory usage: 2.3+ MB

### Find a null value and duplicated value

In [16]:
n2 = df2.isnull().sum()
n2

transaction_id      0
account_id          0
transaction_type    0
amount              0
transaction_date    0
payment_method      0
dtype: int64

In [17]:
d2 = df2.duplicated().sum()
d2

np.int64(0)

### Check Data types

In [18]:
df2.dtypes

transaction_id       object
account_id           object
transaction_type     object
amount              float64
transaction_date     object
payment_method       object
dtype: object

#### Change data type

In [19]:
df2["transaction_date"] = pd.to_datetime(df2["transaction_date"])

In [20]:
df2.dtypes

transaction_id              object
account_id                  object
transaction_type            object
amount                     float64
transaction_date    datetime64[ns]
payment_method              object
dtype: object

In [21]:
df2.to_csv("transaction.csv", index=False)

## 3) Loan_data table

In [22]:
df3 = pd.read_csv('loan_data.csv')
df3.head()

,loan_id,customer_id,loan_type,loan_amount,interest_rate,loan_status,loan_start_date
0,LON_001,CID_920,Business Loan,734389.13,9.31,Approved,25-07-2020
1,LON_002,CID_276,NaN,3755205.17,9.16,Approved,11-05-2019
2,LON_003,CID_4845,Personal,367025.06,9.13,Approved,25-03-2021
3,LON_004,CID_1418,Gold,199739.28,9.19,Approved,27-01-2019
4,LON_005,CID_920,Business Loan,2228549.11,8.96,Approved,10-10-2022

### Check null values  and duplicated values

In [23]:
n3 = df3.isnull().sum()
n3

loan_id              0
customer_id          0
loan_type          120
loan_amount        120
interest_rate      120
loan_status        120
loan_start_date    120
dtype: int64

#### Handling null values

In [24]:
df3["loan_type"].fillna(df3["loan_type"].mode()[0], inplace=True)
df3["loan_amount"].fillna(df3["loan_amount"].mean(), inplace=True)
df3["interest_rate"].fillna(df3["interest_rate"].mean(), inplace=True)
df3["loan_status"].fillna(df3["loan_status"].mode()[0], inplace=True)
df3["loan_start_date"].fillna(method="ffill", inplace=True)

In [25]:
df3.isnull().sum()

loan_id            0
customer_id        0
loan_type          0
loan_amount        0
interest_rate      0
loan_status        0
loan_start_date    0
dtype: int64

In [26]:
d3 = df3.duplicated().sum()
d3

np.int64(0)

### Check Data Type

In [27]:
df3.dtypes

loan_id             object
customer_id         object
loan_type           object
loan_amount        float64
interest_rate      float64
loan_status         object
loan_start_date     object
dtype: object

#### Change data type

In [28]:
df3["loan_start_date"] = pd.to_datetime(df3["loan_start_date"])

In [29]:
df3.dtypes

loan_id                    object
customer_id                object
loan_type                  object
loan_amount               float64
interest_rate             float64
loan_status                object
loan_start_date    datetime64[ns]
dtype: object

In [30]:
df3.to_csv("loan.csv", index=False)

## 4) Accounts_data table

In [32]:
df4 = pd.read_csv('Accounts_Data.csv')
df4.head()

  account_id customer_id account_type    balance account_open_date
0   ACC_0001    CID_0001       Saving  207192.50        28-09-2018
1   ACC_0002    CID_0001      Current  221371.83        28-09-2018
2   ACC_0003    CID_0001        Demat  163023.42        28-09-2018
3   ACC_0004    CID_0002       Saving  191252.30        03-08-2018
4   ACC_0005    CID_0002      Current  910044.45        03-08-2018

### Check Null values and Duplicaed values

In [33]:
n4  = df4.isnull().sum()
n4

account_id           0
customer_id          0
account_type         0
balance              0
account_open_date    0
dtype: int64

In [34]:
d4 = df4.duplicated().sum()
d4

np.int64(0)

### Check Data types

In [35]:
df4.dtypes

account_id            object
customer_id           object
account_type          object
balance              float64
account_open_date     object
dtype: object

#### Change data type

In [36]:
df4["account_open_date"] = pd.to_datetime(df4["account_open_date"])

In [37]:
df4.dtypes

account_id                   object
customer_id                  object
account_type                 object
balance                     float64
account_open_date    datetime64[ns]
dtype: object

In [38]:
df4.to_csv("Accounts.csv", index=False)

## 5) loan_payment_data Table

In [39]:
df5 = pd.read_csv('loan_payment_data.csv')
df5

      payment_id  loan_id payment_amount payment_date
0              1  LON_001      28,245.74   2020-08-10
1              2  LON_001      28,245.74   2020-09-11
2              3  LON_001      28,245.74   2020-10-09
3              4  LON_002      17,208.02   2019-06-14
4              5  LON_002      17,208.02   2019-07-15
...          ...      ...            ...          ...
4995        4996  LON_998      51,731.40   2024-03-19
4996        4997  LON_999      64,765.57   2025-09-27
4997        4998  LON_999      64,765.57   2025-10-27
4998        4999  LON_999      64,765.57   2025-11-26
4999        5000  LON_999      64,412.07   2025-12-26

[5000 rows x 4 columns]

In [40]:
df5.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   payment_id      5000 non-null   int64
 1   loan_id         5000 non-null   object
 2   payment_amount  5000 non-null   object
 3   payment_date    5000 non-null   object
dtypes: int64(1), object(3)
memory usage: 156.4+ KB

### Check null values and Duplicated values

In [41]:
n5 = df5.isnull().sum()
n5

payment_id        0
loan_id           0
payment_amount    0
payment_date      0
dtype: int64

In [42]:
d5 = df5.duplicated().sum()
d5

np.int64(0)

### Check data types

In [43]:
df5.dtypes

payment_id         int64
loan_id           object
payment_amount    object
payment_date      object
dtype: object

### Change Data types

In [44]:
# Remove commas from the column
df5["payment_amount"] = df5["payment_amount"].str.replace(",", "")

In [45]:
df5["payment_amount"] = pd.to_numeric(df5["payment_amount"])

In [46]:
df5["payment_date"] = pd.to_datetime(df5["payment_date"])

In [47]:
df5.dtypes

payment_id                 int64
loan_id                   object
payment_amount           float64
payment_date      datetime64[ns]
dtype: object

In [48]:
df5.to_csv("loan_payment.csv", index=False)

## 6) Complaints_Data Table

In [49]:
df6 = pd.read_csv('complaints_Data.csv')
df6

    complaint_id customer_id      complaint_type  complaint_date       status
0       COMP_001    CID_2733                 NaN           45857         Open
1       COMP_002    CID_1547      Staff Behavior           45996  In Progress
2       COMP_003    CID_2402      Online Banking           44817  In Progress
3       COMP_004    CID_3145      Staff Behavior           45478       Closed
4       COMP_005    CID_1897        Cash Deposit           45900         Open
..           ...         ...                 ...             ...          ...
995     COMP_996    CID_1774   KYC/Documentation           45451     Resolved
996     COMP_997    CID_3366      Staff Behavior           45025         Open
997     COMP_998    CID_4731  Fraud/Unauthorized           45738     Resolved
998     COMP_999    CID_2318  Fraud/Unauthorized           44884     Resolved
999    COMP_1000    CID_4807        Charges/Fees           44244  In Progress

[1000 rows x 5 columns]

In [50]:
df6.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   complaint_id    1000 non-null   object
 1   customer_id     1000 non-null   object
 2   complaint_type  950 non-null    object
 3   complaint_date  1000 non-null   int64
 4   status          950 non-null    object
dtypes: int64(1), object(4)
memory usage: 39.2+ KB

### Check Null values and Duplicated values

In [51]:
n6 = df6.isnull().sum()
n6

complaint_id       0
customer_id        0
complaint_type    50
complaint_date     0
status            50
dtype: int64

### Handling null values

In [52]:
df6["complaint_type"] = df6["complaint_type"].fillna(df6["complaint_type"].mode()[0])
df6["status"] = df6["status"].fillna(df6["status"].mode()[0])

In [53]:
df6.isnull().sum()

complaint_id      0
customer_id       0
complaint_type    0
complaint_date    0
status            0
dtype: int64

In [54]:
d6 = df6.duplicated().sum()
d6

np.int64(0)

### Check data types

In [55]:
df6.dtypes

complaint_id      object
customer_id       object
complaint_type    object
complaint_date     int64
status            object
dtype: object

### Change Data Types

In [56]:
df6["complaint_date"] = pd.to_datetime(df6["complaint_date"])

In [57]:
df6.dtypes

complaint_id              object
customer_id               object
complaint_type            object
complaint_date    datetime64[ns]
status                    object
dtype: object

In [58]:
df6.to_csv("complaints.csv",index = False)